### ISSUE TITLE
cmake file

### ISSUE THREAD

**Issue by MohabMohamed** [MohabMohamed/BtatesCraft#1]
add a cmake file to make us build it on linux not windows only and make a folder for shared libraries .
you can find shared libraries at : BtatesCraft/BtatesCraft/
static libraries at : BtatesCraft/BtatesCraft/lib/
and external header files at : BtatesCraft/BtatesCraft/src/vendor/

**Comment by hrshbh** [comment]
Giving this a shot.

**Comment by MohabMohamed** [comment]
@hrishabh23 ok go for it :D

**Comment by hrshbh** [comment]
PR #2 looks good. Thank you.
I too can't currently contribute to the Windows part. So, the issue is open for the Windows part (and up for grabs).
